name: node
services:
  node:
    type: node
    ssl: true
    build:
      - cp .env.example .env
    command: npm start
    port: 80:80
  postgres:
    type: postgres
    portforward: 5432
    creds:
      database: database